### PR TITLE
Features added: Service and connection port settings, installation of si...

### PR DESCRIPTION
**Pull request by icklers**
For some reason, I fscked up my repository... ;)
I made a few fixes on the facter snippet and fixed the service dependency for the port settings.

This PR includes your fixes on the last PR and my actual fixes.

### CODE REVIEW

**Comment by genebean** [comment]
:+1:

**Comment by genebean** [comment]
Before I make a new release I want to make sure that this fact in here is not going to cause issues on Windows as, right now, it calls `pgrep` before the `confine` can take effect.  Thanks again for the help!

**Comment by genebean** [comment]
@icklers The new version is on the forge now. Please let me know if there are any issues. Thanks again!

**Comment by icklers** [comment]
You're welcome :)

I hope I didn't confuse your versioning and git history :/

**Comment by genebean** [comment]
Nope, it's all good. :-)

**Pull request closed without merging**
