### PR TITLE
Single Networker package installation, service and connection port settings.

### PR DESCRIPTION
**Pull request by icklers**
Hi Gene,

I have added some features to your puppet module and thought it's helpful for everyone to use. ;)

Features:
- Install single packages and modules:
  - Client
  - Server
  - Storagenode
  - NMDA
  - NMSAP
- Specify versions
- Set service and connection ports.

Configurations can be done with hiera:
e.g. 
`networker::install::server: true`
`networker::install::version_server: "8.2.0.1-1"`

I hope everything is documented good enough for you. :)

Cheers,

Sebastian

### CODE REVIEW

**Comment by icklers** [comment]
Fixed a few things for Travis CI checks.. ;)

**Comment by genebean** [comment]
This is awesome and I truly appreciate you sharing!  I do see a few things that need to be adjusted prior to merging though:  
- `checksums.json` is depreciated and should be removed per https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html
- I'm working to get this module to support Windows also so anything you could do with the exec's to make them less OS-dependent that would be great... if not, no biggie.
- On the Travis CI build there were a lot of lint warnings... please take care of these. Most of them can probably be fixed by running `puppet-lint --fix` (I think that's the command anyhow)
- Please bring your version number down to `1.1.0`
- Please remove the edit to the `source` line in `metadata.json` and revert the formatting / ordering change. 
- Please squash your commits

Thanks again and I look forward to merging this!  I'm happy to take suggestions too if any of the above seems off.

**Comment by icklers** [comment]
Hey Gene,

Thanks for your reply. I'm quite new to puppet, module-writing and using git with github/bitbucket, so I will follow your lead and suggestions to succeed. :D 

It all seems like not being a big thing, so I will do it tomorrow. ;)

Maybe I have done the pull request too early for you, but I wanted to share my code for you can use it in your module.
I'm planning to bring it to AIX, too, 'cause that's one use-case I also have. :)

Any wishes for documentation?

**Comment by icklers** [comment]
Ok, this should work now. ;) Warnings gone, work done. ;)
I'm looking into the exec's, but making them OS independent is not that easy for me, because I don't have puppet for windows . I may do it for AIX, as I already mentioned. ;)

**Comment by genebean** [comment]
Certainly not too early for the PR. I'll take a look at what you've done tomorrow (got plans tonight) and see about merging. Thanks again!

**Comment by icklers** [comment]
Fine, you're welcome! :+1: 
If there's any issue, don't hesitate to contact me. :)

**Comment by genebean** [comment]
Been extra busy the last few days, planning to work on merging this tomorrow. Sorry for the delay!

**Comment by genebean** [comment]
I have made a few tweaks to your patch such as remove explicit version numbers from the params file and confining the facter facts to Linux for now. I am going to merge it into the develop branch and would love it if you would test it for me since you seem to have an appropriate setup. Once you give it a once-over I'll close this PR and your code will be merged into master. I need to make a couple of other adjustments before cutting a new release.

**Comment by icklers** [comment]
I wanted to remove the fixed version and changed the default values to "present", so per default the latest available version is installed.

I will test it this week and report back. ;)

**Comment by genebean** [comment]
Thanks!

**Comment by icklers** [comment]
I fixed a few things, especially the custom fact - it didn't work if the nsrexecd isn't running.
I also fixed a dependency regarding the port configuration.

Unfortunately, I can't squash the actual commit :/ Don't know why.

Everything else seems to work fine now.

**Comment by genebean** [comment]
:+1:

**Pull request closed without merging**
